version: '3.8'

services:
  php81-apache:
    build:
      context: .
      dockerfile: Dockerfile.81
    volumes:
      - /home/jesus/proyectos/:/var/www/html/
    ports:
      - 8081:80
    extra_hosts:
      - host.docker.internal:172.20.28.159
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    

