# Build image
FROM php:8.1-apache AS builder

# Set the PATH environment variable
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Copy php.ini
COPY ./conf/php/conf.d/php.ini /usr/local/etc/php/

# Install Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Copy Xdebug configuration
COPY ./conf/php/conf.d/xdebug-322.ini /usr/local/etc/php/conf.d/xdebug.ini

# Install MySQL extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql session

# Install GD extension with support for multiple image formats
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libgif-dev

RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg

RUN docker-php-ext-install -j$(nproc) gd

# Adjust the working directory
WORKDIR /var/www/html

# Copy project files
COPY ./.. /var/www/html

# Change the owner of the container document root
RUN chown -R www-data:www-data /var/www/html

# Add custom virtual host configuration
COPY ./conf/apache2/sites-available/custom-virtual-host.conf /etc/apache2/sites-available/
RUN ln -s /etc/apache2/sites-available/custom-virtual-host.conf /etc/apache2/sites-enabled/

# Enable rewrite mode
RUN a2enmod rewrite

# Start Apache in the foreground
CMD ["apache2-foreground"]
