version: '3.8'
services:
    nges70:
        container_name: php70-apache
        build:
            context: .
            dockerfile: Dockerfile.70
        volumes:
            - /home/jesus/proyectos/:/var/www/html/
        ports:
            - 8070:80
