FROM php:7.4-apache
# RUN docker-php-ext-install -j$(nproc) mysqli && docker-php-ext-enable mysqli
RUN apt-get update -y && apt-get upgrade -y
RUN docker-php-ext-install -j$(nproc) mysqli pdo pdo_mysql && \
  docker-php-ext-enable pdo_mysql
WORKDIR /var/www/html
EXPOSE 80

