version: '3.8'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile.70
        volumes:
            - /home/jesus/proyectos/:/var/www/html/
        networks:
            - mynetwork
    nginx:
        image: nginx:latest
        ports:
            - "8070:80"
        volumes:
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
            - /home/jesus/proyectos/:/var/www/html/
        depends_on:
            - php-fpm
        networks:
            - mynetwork
networks:
    mynetwork:

