version: '3.8'
services:
    nges74:
        container_name: php74-apache
        build:
            context: .
            dockerfile: Dockerfile.74
        volumes:
            - /home/jesus/proyectos/:/var/www/html/
        ports:
            - 8074:80
    nges82:
        container_name: php82-apache
        build:
            context: .
            dockerfile: Dockerfile.82
        volumes:
            - /home/jesus/proyectos/:/var/www/html/
        ports:
            - 8082:80
