version: '3.8'

services:
  php81-apache:
    build:
      context: .
      dockerfile: Dockerfile.81
    volumes:
      - /home/jesus/proyectos/:/var/www/html/
      - ./conf/php/conf.d/xdebug-322.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8081:80
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    

