version: '3.8'
services:
    php-apache-environment:
        container_name: php74-apache
        build:
            context: .
            dockerfile: Dockerfile3.74
        volumes:
            - /home/jesus/proyectos/:/var/www/html/
        ports:
            - 8074:80
