version: '3.8'

services:
  php82-apache:
    build:
      context: .
      dockerfile: Dockerfile.82
    volumes:
      - /home/jesus/proyectos/:/var/www/html/
    ports:
      - 8082:80
    extra_hosts:
      - host.docker.internal:host-gateway 
    

